<?php
/** 
 * @var \Magento\Framework\View\Element\Template $block 
 * @var \Magento\Framework\Escaper $escaper
 * @var \Bootcamp\PruebaApi\ViewModel\RickAndMortyViewModel $viewModel
 * */


$viewModel = $block->getData('view_model');
?>
 <h1>PRUEBAS</h1>
<?php if($viewModel->getEnabled()): ?>
<h1><?= $escaper->escapeHtml(__("Rick and Morty Characters")) ?></h1>

<div class="characters">
    <?php foreach( $viewModel->getCharacters() as $character ): ?>
        <div class="character-item">
            <h2 class="character-name"><?= $escaper->escapeHtml($character['name']) ?></h2>
            <div class="character-img">
                <img src="<?= $escaper->escapeUrl($character['image']) ?>" alt="<?= $escaper->escapeHtml($character['name']) ?>">
            </div>
            <div class="character-description">
                <div class="character-status"><?= $escaper->escapeHtml($character['status']) ?></div>
                <div class="character-type"><?= $escaper->escapeHtml($character['type']) ?></div>
                <div class="character-species"><?= $escaper->escapeHtml($character['species']) ?></div>
                <div class="character-gender"><?= $escaper->escapeHtml($character['gender']) ?></div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<?php else: ?>
<h1><?= $escaper->escapeHtml(__("Rick And Morty App is disabled")) ?></h1>
<?php endif; ?>