<?php

/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="fondo">
    <img class="img-fondo" sytle="width: 100%; height: 100vh;" src="<?= $this->getViewFileUrl('images/fondo.png') ?>" alt="Fondo">
</div>
    <div class="content-horario">
        <div class="img-horario">
            <img src="<?= $this->getViewFileUrl('images/HORARIO-PANAFOTO-V2.webp') ?>" alt="" srcset="">
        </div>
        <div class="tabla-horario">
            <table style="height: 572px; width: 651px; border-color: #000000; margin-left: auto; margin-right: auto;" border="1">
                <tbody>
                    <tr style="height: 54px;">
                        <td style="width: 156.883px; text-align: center; height: 54px;"><span style="font-size: 18px; color: #800000;"><strong><?= $escaper->escapeHtml("Sucursales") ?></strong></span></td>
                        <td style="width: 198.483px; text-align: center;"><span style="font-size: 18px; color: #800000;"><strong><?= $escaper->escapeHtml("Horario") ?> <br><?= $escaper->escapeHtml("Lunes a Sábado") ?></strong></span></td>
                        <td style="width: 198.65px; height: 54px; text-align: center;"><span style="font-size: 18px; color: #800000;"><strong><?= $escaper->escapeHtml("Horario") ?> <br><?= $escaper->escapeHtml("Domingo") ?><br></strong></span></td>
                        <td style="width: 95.9833px; height: 54px; text-align: center;"><span style="font-size: 18px; color: #800000;"><strong><?= $escaper->escapeHtml("Ubicación") ?></strong></span></td>
                    </tr>
                    <tr style="height: 45px;">
                        <td style="width: 156.883px; height: 45px; text-align: center;"><span style="font-size: 18px;"><strong><?= $escaper->escapeHtml("Albrook Mall") ?><br><?= $escaper->escapeHtml("Tel: 314-6780") ?><br></strong></span></td>
                        <td style="width: 198.483px;">
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; text-align: center; margin: 0px;" align="center"><strong><span style="color: black !important; font-size: 18px;"><?= $escaper->escapeHtml("10:00 a.m. a 8:00 p.m.") ?></span></strong></p>
                        </td>
                        <td style="width: 198.65px; height: 45px;"><span style="font-size: 16px;"><strong><?= $escaper->escapeHtml("11:00 a.m. a 7:00 p.m.") ?></strong></span></td>
                        <td style="width: 95.9833px; height: 45px; text-align: center;"><span style="font-size: 16px;"><a tabindex="0" href="https://www.waze.com/en/live-map/directions/panafoto-or-albrook-mall-ciudad-de-panama?place=w.183763034.1837958018.11667824" target="_blank" rel="noopener"><span style="color: black !important;">Ver Mapa</span></a></span></td>
                    </tr>
                    <tr style="height: 43px;">
                        <td style="width: 156.883px; height: 43px; text-align: center;"><span style="font-size: 18px;"><strong><?= $escaper->escapeHtml("Multiplaza") ?><br><?= $escaper->escapeHtml("Tel: 302-1100") ?><br></strong></span></td>
                        <td style="width: 198.483px;">
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; text-align: center; margin: 0px;" align="center"><strong><span style="color: black !important; font-size: 18px;"><?= $escaper->escapeHtml("10:00 a.m. a 8:00 p.m.") ?></span></strong></p>
                        </td>
                        <td style="width: 198.65px; height: 43px;"><span style="font-size: 16px;"><strong><?= $escaper->escapeHtml("11:00 a.m. a 7:00 p.m.") ?></strong></span></td>
                        <td style="width: 95.9833px; height: 43px; text-align: center;"><span style="font-size: 16px;"><a tabindex="0" href="https://www.waze.com/en/live-map/directions/panafoto-multiplaza-centro-comercial-multiplaza-pacific-ciudad-de-panama?place=w.183828570.1838220163.16999896" target="_blank" rel="noopener"><span style="color: black !important;"><?= $escaper->escapeHtml("Ver Mapa") ?></span></a></span></td>
                    </tr>
                    <tr style="height: 44px;">
                        <td style="width: 156.883px; height: 44px; text-align: center;"><span style="font-size: 18px;"><strong><?= $escaper->escapeHtml("Centennial") ?><br> <?= $escaper->escapeHtml("Tel: 230-5205") ?><br></strong></span></td>
                        <td style="width: 198.483px;">
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; text-align: center; margin: 0px;" align="center"><strong><span style="color: black !important; font-size: 18px;"><?= $escaper->escapeHtml("10:00 a.m. a 8:00 p.m.") ?></span></strong></p>
                        </td>
                        <td style="width: 198.65px; height: 44px;"><span style="font-size: 16px;"><strong><?= $escaper->escapeHtml("11:00 a.m. a 7:00 p.m.") ?></strong></span></td>
                        <td style="width: 95.9833px; height: 44px; text-align: center;"><span style="font-size: 16px;"><a tabindex="0" href="https://www.waze.com/en/live-map/directions/panafoto-centennial-ruta-4-av.-universidad-tecnologica-123-ciudad-de-panama?place=w.183828570.1838089095.13373861" target="_blank" rel="noopener"><span style="color: black !important;"><?= $escaper->escapeHtml("Ver Mapa") ?></span></a></span></td>
                    </tr>
                    <tr style="height: 44px;">
                        <td style="width: 156.883px; height: 44px; text-align: center;"><span style="font-size: 18px;"><strong><?= $escaper->escapeHtml("Metromall") ?><br><?= $escaper->escapeHtml("Tel: 217-7739") ?><br></strong></span></td>
                        <td style="width: 198.483px;">
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; text-align: center; margin: 0px;" align="center"><strong><span style="color: black !important; font-size: 18px;"><?= $escaper->escapeHtml("10:00 a.m. a 8:00 p.m.") ?></span></strong></p>
                        </td>
                        <td style="width: 198.65px; height: 44px;"><span style="font-size: 16px;"><strong><?= $escaper->escapeHtml("11:00 a.m. a 7:00 p.m") ?>.</strong></span></td>
                        <td style="width: 95.9833px; height: 44px; text-align: center;"><span style="font-size: 16px;"><a tabindex="0" href="https://www.waze.com/en/live-map/directions/panafoto-metromall?place=w.183828571.1838613385.7424549" target="_blank" rel="noopener"><span style="color: black !important;"><?= $escaper->escapeHtml("Ver Mapa") ?></span></a></span></td>
                    </tr>
                    <tr style="height: 43px;">
                        <td style="width: 156.883px; height: 43px; text-align: center;"><span style="font-size: 18px;"><strong><?= $escaper->escapeHtml("Calle 50") ?><br><?= $escaper->escapeHtml("Tel: 263-3000") ?><br></strong></span></td>
                        <td style="width: 198.483px;">
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; text-align: center; margin: 0px;" align="center"><strong><span style="color: black !important; font-size: 18px;"><?= $escaper->escapeHtml("9:00 a.m. a 7:00 p.m.") ?></span></strong></p>
                        </td>
                        <td style="width: 198.65px; height: 43px;"><span style="font-size: 16px;"><strong><?= $escaper->escapeHtml("11:00 a.m. a 6:00 p.m.") ?></strong></span></td>
                        <td style="width: 95.9833px; height: 43px; text-align: center;"><span style="font-size: 16px;"><a tabindex="0" href="https://www.waze.com/en/live-map/directions/panafoto-calle-50-ciudad-de-panama?place=w.183828570.1838154626.416999" target="_blank" rel="noopener"><span style="color: black !important;"><?= $escaper->escapeHtml("er Mapa") ?>V</span></a></span></td>
                    </tr>
                    <tr style="height: 43px;">
                        <td style="width: 156.883px; height: 43px; text-align: center;"><span style="font-size: 18px;"><strong><?= $escaper->escapeHtml("Santa María") ?><br><?= $escaper->escapeHtml("Tel: 830-7905") ?></strong><span style="color: black !important;"><br></span></span></td>
                        <td style="width: 198.483px; text-align: center;">
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; text-align: center; margin: 0px;" align="center"><strong><span style="color: black !important; font-size: 18px;"><?= $escaper->escapeHtml("10:00 a.m. a 7:30 p.m.") ?></span></strong></p>
                        </td>
                        <td style="width: 198.65px; height: 43px; text-align: center;"><span style="font-size: 16px;"><strong><?= $escaper->escapeHtml("11:00 a.m. a 6:00 p.m.") ?></strong></span></td>
                        <td style="width: 95.9833px; height: 43px; text-align: center;"><span style="font-size: 16px;"><a tabindex="0" href="https://www.waze.com/en/live-map/directions/panafoto-or-santa-maria-blvd.-oeste-ciudad-de-panama?place=w.183828570.1838482311.13672399" target="_blank" rel="noopener"><span style="color: black !important;"><?= $escaper->escapeHtml("Ver Mapa") ?></span></a></span></td>
                    </tr>
                    <tr style="height: 116px;">
                        <td style="width: 156.883px; height: 116px; text-align: center;"><span style="font-size: 18px;"><strong><?= $escaper->escapeHtml("Colón 2000") ?><br><?= $escaper->escapeHtml("Tel: 433-3586") ?><br></strong></span></td>
                        <td style="width: 198.483px;">
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; text-align: center; margin: 0px; text-align:center"><span id="FM1SC8G" style="color: black !important; font-size: 18px;"><strong><span style="color: #993300;"><?= $escaper->escapeHtml("Lunes a Viernes") ?></span></strong><br><strong><?= $escaper->escapeHtml("9:30 a.m. a 6:30 p.m.") ?></strong><br><strong><span style="color: #993300;"><?= $escaper->escapeHtml("Sábados") ?></span></strong><br><strong><?= $escaper->escapeHtml("9:00 a.m. a 6:00 p.m") ?></strong>.</span></p>
                        </td>
                        <td style="width: 198.65px; height: 116px;"><span style="color: #993300; font-size: 16px;"><strong><?= $escaper->escapeHtml("CERRADO") ?></strong></span></td>
                        <td style="width: 95.9833px; height: 116px; text-align: center;"><span style="font-size: 16px;"><a tabindex="0" href="https://www.waze.com/en/live-map/directions/panafoto-colon-2000-paseo-doctor-gorgas-colon?place=w.183566430.1835729832.22014394" target="_blank" rel="noopener"><span style="color: black !important;"><?= $escaper->escapeHtml("Ver Mapa") ?></span></a></span></td>
                    </tr>
                    <tr style="height: 47px;">
                        <td style="width: 156.883px; height: 47px; text-align: center;"><span style="font-size: 18px;"><strong><?= $escaper->escapeHtml("Costa Verde, La Chorrera") ?><br><?= $escaper->escapeHtml("Tel: 830-9724") ?><br></strong></span></td>
                        <td style="width: 198.483px;">
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; text-align: center; margin: 0px;" align="center"><strong><span style="color: black !important; font-size: 18px;"><?= $escaper->escapeHtml("10:00 a.m. a 8:00 p.m.") ?></span></strong></p>
                        </td>
                        <td style="width: 198.65px; height: 47px;"><span style="font-size: 16px;"><strong><?= $escaper->escapeHtml("11:00 a.m. a 7:00 p.m.") ?></strong></span></td>
                        <td style="width: 95.9833px; height: 47px; text-align: center;"><span style="font-size: 16px;"><a tabindex="0" href="https://www.waze.com/en/live-map/directions/panafoto-costa-verde-costa-verde,-la-chorrera?place=w.183631961.1836647289.7909760" target="_blank" rel="noopener"><span style="color: black !important;"><?= $escaper->escapeHtml("Ver Mapa") ?></span></a></span></td>
                    </tr>
                    <tr style="height: 44px;">
                        <td style="width: 156.883px; height: 44px; text-align: center;"><span style="font-size: 18px;"><strong><?= $escaper->escapeHtml("Santiago, Veraguas") ?><br><?= $escaper->escapeHtml("Tel: 998-7001") ?><br><?= $escaper->escapeHtml("998-6212") ?><br></strong></span></td>
                        <td style="width: 198.483px;">
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; text-align: center; margin: 0px;" align="center"><strong><span style="color: black !important; font-size: 18px;"><?= $escaper->escapeHtml("9:00 a.m. a 7:00 p.m.") ?></span></strong></p>
                        </td>
                        <td style="width: 198.65px; height: 44px;"><span style="font-size: 16px;"><strong><?= $escaper->escapeHtml("10:00 a.m. a 6:00 p.m.") ?></strong></span></td>
                        <td style="width: 95.9833px; height: 44px; text-align: center;"><span style="font-size: 16px;"><a tabindex="0" href="https://www.waze.com/en/live-map/directions/panafotoor-santiago-santiago,-veraguas?place=w.182845521.1828651819.4608391" target="_blank" rel="noopener"><span style="color: black !important;"><?= $escaper->escapeHtml("Ver Mapa") ?></span></a></span></td>
                    </tr>
                    <tr style="height: 46px;">
                        <td style="width: 156.883px; height: 46px; text-align: center;"><span style="font-size: 18px;"><strong><?= $escaper->escapeHtml("Terronal, Chiriquí") ?><br><?= $escaper->escapeHtml("Tel: 774-1010") ?><br></strong></span></td>
                        <td style="width: 198.483px; text-align: center;">
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; text-align: center; margin: 0px;" align="center"><strong><span id="LN3VF2D" style="color: black !important; font-size: 18px;"><?= $escaper->escapeHtml("10:00 a.m. a 8:00 p.m.") ?></span></strong></p>
                        </td>
                        <td style="width: 198.65px; height: 46px; text-align: center;"><span style="font-size: 16px;"><strong><?= $escaper->escapeHtml("11:00 a.m. a 7:00 p.m.") ?></strong></span></td>
                        <td style="width: 95.9833px; height: 46px; text-align: center;"><span style="font-size: 16px;"><a tabindex="0" href="https://www.waze.com/en/live-map/directions/panama/provincia-de-chiriqui/david/panafoto-or-david?place=ChIJ8XRuzxqdpY8RZTsMdWmx0pA" target="_blank" rel="noopener"><span style="color: black !important;"><?= $escaper->escapeHtml("Ver") ?></span><span style="color: black !important;"><?= $escaper->escapeHtml("Mapa") ?></span></a></span></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
